### ISSUE TITLE
7-zip 9.20 fails to extract zip produced by yazl

### ISSUE THREAD

**Issue by joaomoreno** [thejoshwolfe/yazl#11]
My script creates the simplest zip file possible:

```javascript
var yazl = require('yazl');
var fs = require('fs');

var zipfile = new yazl.ZipFile();

var ostream = fs.createWriteStream('out.zip');
zipfile.outputStream.pipe(ostream);

zipfile.addBuffer(new Buffer('hello'), 'hello.txt');
zipfile.end();
```

I cannot extract this file with [7-zip](http://www.7-zip.org/) 9.20 (its latest stable release). This application has a feature that verifies an archive and with the produced zip I get:

![screen shot 2015-03-19 at 16 01 09](https://cloud.githubusercontent.com/assets/22350/6733255/4a842858-ce51-11e4-97d9-74636ee50054.png)

I can successfully extract it using the native Windows `Extract...` context menu action. I can also extract it using 7-zip 9.38 (their latest beta release).

**Comment by thejoshwolfe** [comment]
I've reproduced this issue. It is difficult to be motivated to do anything in response to this, knowing that the next version of 7-zip fixes what appears to be their incompatibility with the zip file spec.

I'll play around with the old (stable) version of 7-zip to see if there's something easy to be done about it.

**Comment by joaomoreno** [comment]
Thanks, I'd be awesome to nail it, since many users are still on 9.20 and there's no automatic update feature in that app. :+1:

**Comment by thejoshwolfe** [comment]
I've determined that 7-zip 9.20 does not support general purpose bit 3. see https://github.com/thejoshwolfe/yazl/blob/master/README.md#general-purpose-bit-flag for why yazl relies on general purpose bit 3 being supported. See also #13 (opened in response to this issue).

**Comment by thejoshwolfe** [comment]
here was my test to determine that 7-zip 9.20 does not support general purpose bit 3:

http://wolfesoftware.com/zip_without_general_purpose_bit_3.zip

http://wolfesoftware.com/zip_with_general_purpose_bit_3.zip

**Comment by thejoshwolfe** [comment]
version 2.2.0 is published. see the note here for how to create zip files with yazl that 7-Zip 9.20 can read: https://github.com/thejoshwolfe/yazl/blob/master/README.md#addbufferbuffer-metadatapath-options
