### ISSUE TITLE
Avoid using general purpose bit 3 when possible

### ISSUE THREAD

**Issue by thejoshwolfe** [thejoshwolfe/yazl#13]
7-zip 9.20 seems to not support general purpose bit 3. It wouldn't be too difficult to avoid relying on general purpose bit 3 sometimes, for example when a file is added with `addBuffer()`.

Enhancing `addBuffer()` to avoid general purpose bit 3 will enable users to have compatibility with 7-zip 9.20 by buffering their files in ram and using `addBuffer()` exclusively.

**Comment by joaomoreno** [comment]
Great stuff! :+1:

**Comment by joaomoreno** [comment]
@thejoshwolfe 

> Mac's Archive Utility requires File Descriptors to include the optional signature, so yazl includes the optional file descriptor signature.

It appears that it's not possible to create an archive with yazl that can be extracted by both Mac's Archive Utility and 7-Zip 9.20. Is this correct?

How could we make this work for both applications?

**Comment by andrewrk** [comment]
If you use the `addBuffer` API, it avoids using general purpose bit 3, which works around the bug in 7-Zip 9.20. This is unrelated to the optional file descriptor signature.

**Comment by joaomoreno** [comment]
Then unfortunately there might've been an oversight on the latest release. I've created #14 to track this.
