### ISSUE TITLE
OS X Archive Utility fails to extract zip file

### ISSUE THREAD

**Issue by joaomoreno** [thejoshwolfe/yazl#14]
With the latest version `2.2.0` the following code produces a zip file that OS X's Archive Utility cannot open:

```javascript
var yazl = require('yazl');
var fs = require('fs');

var zipfile = new yazl.ZipFile();

var ostream = fs.createWriteStream('out.zip');
zipfile.outputStream.pipe(ostream);

zipfile.addBuffer(new Buffer('hello'), 'hello.txt');
zipfile.end();
```

![screen shot 2015-03-26 at 20 51 24](https://cloud.githubusercontent.com/assets/22350/6855585/e19d8272-d3f9-11e4-8498-4ef409e28327.png)

**System log**

```
26/03/15 20:51:23.972 Archive Utility[29825]: bomCopierFatalError:Couldn't read pkzip signature.
26/03/15 20:51:23.973 Archive Utility[29825]: bomCopierFatalError:Not a central directory signature
```

**Comment by RickyChien** [comment]
I ran into the same issue with Archive Utility but worked with The archiver or ```unzip xxx``` from terminal.

**Comment by thejoshwolfe** [comment]
I've reproduced this problem.

**Comment by thejoshwolfe** [comment]
@joaomoreno I believe I've fixed this issue. Please let me know if you run into any more trouble.

**Comment by RickyChien** [comment]
@thejoshwolfe NPM package hasn't updated yet =)

**Comment by thejoshwolfe** [comment]
Ah, sorry. updated now.

**Comment by joaomoreno** [comment]
Confirmed that it works for both Archive Utility and 7-Zip 9.20. :+1:
