### ISSUE TITLE
Issues when extracting with OSX Archive

### ISSUE THREAD

**Issue by paulgoldbaum** [thejoshwolfe/yazl#24]
When extracting zip files generated with yazl 2.4.0 using the Archive app, a filename.zip.cpgz is generated instead of the contents. Zipfiles generated with 2.3.1 work as expected.

I'm using yazl through gulp-zip so it might not be an issue with yazl itself.

**Comment by mkalish** [comment]
+1

**Comment by Sryther** [comment]
+1

If you rename the file into .rar it works..

**Comment by thejoshwolfe** [comment]
sorry about this guys. i lost my mac test machine recently, and i didn't suspect that changing the Version Needed To Extract would break anything so i published without testing that on Mac. if one if you would be willing to try out some test case zipfiles i upload in a few minutes, that would be most appreciated...

**Comment by thejoshwolfe** [comment]
Could someone on Mac please try extracting these four zipfiles:

http://wolfesoftware.com/tests.zip

(the zip contains 4 zips, which each contain a single empty file.)

Please tell me which zip files extract, if any, and which cause the .cpgz behavior. This will determine if the Version Made By and Version Needed To Extract are the culprits. I suspect only the Version Needed To Extract will be the problem.

**Comment by mkalish** [comment]
1 and 2 both worked
3 and 4 did not

**Comment by mkalish** [comment]
👍

**Comment by thejoshwolfe** [comment]
thanks @mkalish for your help.

yazl version 2.4.1 is published and should fix this issue.
