### ISSUE TITLE
unzip, edit and re-zip

### ISSUE THREAD

**Issue by nalbion** [thejoshwolfe/yazl#30]
Hi, not so much of a bug, but a question/request for assistance...  I'm trying to create a gulp plugin which edits an entry within a zip file.

I didn't have any luck with yauzl, (it complained of an invalid signature when provided with a zip file created by yazl) so I'm using the `[unzip](https://github.com/EvanOxfeld/node-unzip)` package.

I'd really appreciate it if you could take a quick look at the code below and help me figure out how to update the zip 
"file" with the updated file, leaving all other files intact.

```javascript
var through = require('through2');
var yazl = require('yazl');
var unzip = require('unzip');

module.exports = function() {
    function transformZipFile(file, encoding, callback) {

    file.pipe(unzip.Parse())
            .on('entry', function(entry) {
                if (entry.path === 'lib/env-config.js') {
                    entry.pipe(through.obj(transformEnvConfig, function(flushCallback) {
                        // not sure what to do here - I have 2 callbacks which need to be called (not sure what flushCallback does
                        // I'm not sure if the entry is writable, if I need to update a zip header if I do...
                        // If the entry is not writable, I suppose I need to copy across all of the other files as well as this one to the new output zip archive

                        flushCallback();
                        callback(null, file);
                    }));
                } else {
                    entry.autodrain();
                }
            })
            .on('close', function() {
                console.info('unzip closed');

            });
    }

   function transformEnvConfig(data, encoding, callback) {
        deployEnvConfig.updateEnvConfigData(data.toString()).then( function(newEnvConfigData) {
            console.info('env-config updated');
            // newEnvConfig is correctly updated, now I need to write it back to the zip "file"
            callback(null, newEnvConfigData);
        }, callback);
    }

    return through.obj(transformZipFile);
};
```

**Comment by thejoshwolfe** [comment]
> I didn't have any luck with yauzl, (it complained of an invalid signature when provided with a zip file created by yazl) so I'm using the [unzip](https://github.com/EvanOxfeld/node-unzip) package.

Oh no! Sounds like you found a bug in yauzl or yazl. Can you elaborate more on that? Would you open an issue describing that experience? Those two modules are definitely supposed to work together. I made both of them, and they're both (supposed to be) standards compliant.

Your code looks tightly integrated with `unzip` and `through2`. I'm not sure what kind of support you're looking for from me on that, but I can tell you how to use yazl and yauzl.

The general design of yazl is that it always produces an output stream. This is unsuitable for doing in-place edits to a zipfile through a read-write random-access file descriptor (like a normal file on a file system).

In general, the zipfile format *was* designed to be friendly to in-place edits. The spec even says "Files may be added or replaced within a ZIP file, or deleted." (4.3.1). However, in modern times, the in-place edit usecase is exceedingly rare. It sounds like you may be one of the few who wants to do it. yazl was designed for the common case of creating an entire zipfile from individual uncompressed files in one go.

A zipfile in-place editor would have a very different design than either yazl or yauzl has, and there are many complex issues to approach in that domain. For example, if you increase the size of an entry, you need to either move the entry to the end of the file, or shift all the entries that follow that entry, and if you shrink an entry, you're left with unused space between entries.

Or maybe you're not talking about in-place edits at all. Maybe you really just mean completely unzipping and re-zipping every entry in a zipfile. This approach will work with existing code fairly easily, but of course comes with the performance implications of needlessly decompressing and re-compressing all the entries in the zipfile that you're not planning to change. I can give you some example code that does that with yauzl and yazl if you'd like.

**Comment by nalbion** [comment]
Thanks for your response @thejoshwolfe. I've figured out that my problem was due to following the example code (without 100% understanding it):

```javascript

```yauzl.fromBuffer(file._contents, function(err, zipFile) {
            if (err) {
                console.info('yauzl failed to unzip:', err);
                callback(err);
            } else {
// with this line uncommented I get an error "invalid central directory file header signature: 0x2f62696c"
//                zipFile.readEntry();
// ...but without it, it's work as well as `unzip`
                zipFile.on('entry', function(entry) {
                    if (entry.fileName === 'lib/env-config.js') {
                        zipFile.openReadStream(entry, function(err, readStream) {
                            if (err) {
                                console.error('Failed to read env-config:', err);
                                callback(err);
                            } else {
                                readStream.pipe(through.obj(transformEnvConfig, function(flushCallback) {

                                    // still stuck for what to do here...

                                    flushCallback();
                                    callback(null);
                                }));
                            }
                        });
                    }
                });
                zipFile.on('error', callback);
            }
        });

**Comment by nalbion** [comment]
...to answer your question - yes, what I was hoping for was to do an in-place edit on the buffer/stream.

[adm-zip](https://github.com/cthackers/adm-zip) claims to be able to do it:

> update content of/add new/delete files from an existing .zip

...but the library hasn't been touched for a couple of years (maybe it doesn't need to be?)

Apparently, the constructor accepts a Buffer (not documented) - https://github.com/cthackers/adm-zip/issues/158

**Comment by thejoshwolfe** [comment]
looks like adm-zip decompresses and recompresses all the file contents when you do what looks like an in-place edit, but it's hard to say. There's no documentation for that library, except for a single example. It looks like the focus of that project was to get something working at all that had an API that looked like what they wanted to do. Since they don't document anything about performance or implementation strategy (or even the details of the API), they don't appear to care about such things. (At least we can tell from the [npm usage](https://www.npmjs.com/package/adm-zip) that the project seems to work at all.) I would not use such a library, but then again, I'm pretty picky and cynical about projects with bad documentation, so that might just be my bias.

If you're looking for something that performs better than naively decompressing and recompressing everything, then you should make sure that the project you choose actually does better than that. It's entirely possible that adm-zip does better than that, but if so, it's not documented. Reading documentation is generally easier than creating and running tests, but in the absence of documentation, testing might be your only option.

Another suspicion I have about adm-zip is that they might be buffering the entire zipfile in a ram buffer. Or if not the entire zipfile, then at least entire file entries. You might want to test with a large zipfile or with a zipfile with large entries if that is a realistic usecase for you.

If you'd like help getting a yauzl -> yazl transformation going, I can help with that. I'm not an expert on gulp, so I'd be best able to help with a pure yauzl+yazl example program; hooking that into gulp would be left for you to do. Let me know if you're interested in this.

**Comment by nalbion** [comment]
`adm-zip` was looking promising, until I went to update the zip file, I got an error: "Invalid LOC header (bad signature)".

```javascript
var AdmZip = require('adm-zip');
var admZip = new AdmZip(file._contents);
transformEnvConfig(admZip.readFile(envConfigFileName), null, function(err, updated) {
    if (err) {
        callback(err);
    } else {
        admZip.updateFile(envConfigFileName, new Buffer(updated, 'utf8'));

        // Error: "Invalid LOC header (bad signature)"
        admZip.toBuffer(function(buffer) {
            console.info('env-config.zip updated', buffer);
            callback();
        }, callback);

        // uses the same codde as toBuffer, throws the same error:
        // admZip.writeZip('/tmp/adm-zip/env-config.zip', callback);
    }
});
```

I'm [not the first person to run into this](https://github.com/cthackers/adm-zip/issues/64#issuecomment-234300084), and the work-around is to create a new zip archive

**Comment by nalbion** [comment]
My yauzl snippet above could probably be simplified a little.

Ultimately, I need to provide the gulp callback with either a Stream or Buffer representing the updated zip archive.

https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/README.md

**Comment by nalbion** [comment]
Cracked it!!

```javascript
var through = require('through2');
var yauzl = require('yauzl');
var yazl = require('yazl');
var deployEnvConfig = require('../lib/deploy-env-config');

module.exports = function() {
    function transformZipFile(file, encoding, callback) {
        console.info('updating env-config for', file.relative + '...');
        var envConfigFileName = 'lib/env-config.js';

        yauzl.fromBuffer(file._contents, function(err, originalZipFile) {
            if (err) {
                console.info('yauzl failed to unzip:', err);
                callback(err);
            } else {
                var newZipFile = new yazl.ZipFile();

                var pendingEntries = originalZipFile.entryCount;
                var checkIfDone = function() {
                    if (--pendingEntries == 0) {
                        newZipFile.end(function() {
                            console.info('sending updated', file.relative, 'to next stage');
                            file.contents = newZipFile.outputStream;
                            callback(null, file);
                        });
                    }
                };

                originalZipFile.on('entry', function(entry) {
                    if (entry.fileName === envConfigFileName) {
                        originalZipFile.openReadStream(entry, function(err, readStream) {
                            if (err) {
                                console.error('Failed to read env-config:', err);
                                callback(err);
                            } else {
                                // transformEnvConfig() provides the updated env-config as a string
                                readStream.pipe(through.obj(transformEnvConfig))
                                    .on('data', function(data) {
                                        newZipFile.addBuffer(new Buffer(data), entry.fileName);
                                        checkIfDone();
                                    });
                            }
                        });
                    } else {
                        originalZipFile.openReadStream(entry, function(err, readStream) {
                            newZipFile.addReadStream(readStream, entry.fileName);
                            checkIfDone();
                        });
                    }
                });
            }
        });
    }

    /**
     * @param {Buffer} data
     * @param {String} encoding - not used
     * @param callback
     */
    function transformEnvConfig(data, encoding, callback) {
        deployEnvConfig.updateEnvConfigData(data.toString()).then( function(newEnvConfigData) {
            console.info('...env-config successfully updated');
            callback(null, newEnvConfigData);
        }, callback);
    }

    return through.obj(transformZipFile);
};
```
