### ISSUE TITLE
Support for adding directories

### ISSUE THREAD

**Issue by julien-f** [thejoshwolfe/yazl#39]
I believe this is a classic use case and it would be nice to have it directly in this module.

Here's what I currently do:

```js
var fs = require("fs");
var path = require("path");
var yazl = require("yazl");

var noop = Function.prototype;

function addDirectory(zip, realPath, metadataPath, cb) {
  fs.readdir(realPath, function(error, files) {
    if (error == null) {
      var i = files.length;
      var resolve = function(error) {
        if (error != null) {
          resolve = noop;
          cb(error);
        } else if (--i === 0) {
          resolve = noop;
          cb();
        }
      };
      files.forEach(function(file) {
        addDirectory(
          zip,
          path.join(realPath, file),
          metadataPath + "/" + file,
          resolve
        );
      });
    } else if (error.code === "ENOTDIR") {
      zip.addFile(realPath, metadataPath);
      cb();
    } else {
      cb(error);
    }
  });
}

var zip = new yazl.ZipFile();

addDirectory(zip, "./my-directory", "my-directory", function(error) {
  if (error) {
    return console.error(error);
  }

  zip.end();
  zip.outputStream.pipe(fs.createWriteStream("./archive.zip"));
});

**Comment by thejoshwolfe** [comment]
Nice code! I like that code a lot.

You're not the first to suggest this feature. My feeling about this is that directory traversal is outside the scope of this module. Let me explain.

As your code shows, this feature can be accomplished by building on top of yazl. yazl was designed to be a low-level component on which you can build abstractions without yazl introducing any unnecessary overhead. Your code is a good example of this principle at work.

Anything included in yazl is something that I have to maintain. Directory traversal can actually become a pretty complicated problem. Some features that people might ask me to add:

 * follow symlinks or not
 * detect fs cycles and report an error or silently ignore
 * exclude OS-specific hidden things by default like `__MACOSX` or `Thumbs.db`
 * configurable exclude patterns, e.g. `/^\.|~$/`
 * configurable include patterns?

You can see how these have anything to do with creating zip files, which is what yazl is really all about.

A very common usecase for zip files is capturing the state of a file system, and indeed zip files were designed with this usecase in mind. But if yazl tries to be a file system archiving utility, then yazl needs to know about file systems and their quirks. Currently, yazl does very little in this regard, specifically mtime and permission bits during `addFile()`. I feel like those are common enough features of any file system that it's worth supporting them here. But I hope I've made my point about how directory traversal starts treading into scarier territory. There are even potential security vulnerabilities tangled up in this concept that I don't want to be responsible for.

I encourage someone (it could even be you!) to make a node module that combines directory traversal with yazl to provide the feature you're looking for, or maybe this already been done. But I don't think this function belongs in yazl itself.

**Comment by julien-f** [comment]
Most of these questions could be answered by a filter predicate receiving the path and the lstats of the entry but I understand :slightly_smiling_face: 

I just wanted to share this code in case it might help someone.

Have a nice day.

**Comment by julien-f** [comment]
For the fun, a version with the filter predicate:

```js
var fs = require("fs");
var path = require("path");
var yazl = require("yazl");

var noop = Function.prototype;

const IGNORED_FILES = {
  __proto__: null,

  "$RECYCLE.BIN": true,
  "ehthumbs_vista.db": true,
  "ehthumbs.db": true,
  "Thumbs.db": true
};

function defaultFilter(realPath, stats) {
  var basename = path.basename(realPath);
  return !(basename[0] === "." || basename in IGNORED_FILES);
}

function addDirectory(zip, realPath, metadataPath, filter, cb) {
  if (cb === undefined) {
    cb = filter;
    filter = defaultFilter;
  } else if (filter == null) {
    filter = defaultFilter;
  }

  fs.lstat(realPath, function(error, stats) {
    if (error != null) {
      return cb(error);
    }

    if (stats.isDirectory() && filter(realPath, stats)) {
      fs.readdir(realPath, function(error, files) {
        if (error != null) {
          return cb(error);
        }

        var i = files.length;
        var resolve = function(error) {
          if (error != null) {
            resolve = noop;
            cb(error);
          } else if (--i === 0) {
            resolve = noop;
            cb();
          }
        };
        files.forEach(function(file) {
          addDirectory(
            zip,
            path.join(realPath, file),
            metadataPath + "/" + file,
            filter,
            resolve
          );
        });
      });
    } else if (stats.isFile() && filter(realPath, stats)) {
      zip.addFile(realPath, metadataPath);
      cb();
    } else if (stats.isSymbolicLink() && filter(realPath, stats)) {
      return fs.readlink(realPath, function(error, target) {
        if (error != null) {
          return cb(error);
        }
        addDirectory(
          zip,
          path.resolve(path.dirname(realPath), target),
          metadataPath,
          filter,
          cb
        );
      });
    } else {
      cb(); // ignored types
    }
  });
}

var zip = new yazl.ZipFile();

addDirectory(
  zip,
  "./my-directory",
  "my-directory",
  function(realPath, stats) {
    return !stats.isSymbolicLink() && defaultFilter(realPath, stats);
  },
  function(error) {
    if (error) {
      return console.error(error);
    }

    zip.end();
    zip.outputStream.pipe(fs.createWriteStream("./archive.zip"));
  }
);
```
