### ISSUE TITLE
2.5.0 TypeError: this is not a typed array

### ISSUE THREAD

**Issue by chadn** [thejoshwolfe/yazl#47]
We use gulp-zip which uses yazl and a few days ago our build broke because of changes in 2.5.0
Here's the error 
```
node_modules/gulp-zip/node_modules/yazl/index.js:111
var eocdrSignatureBuffer = Buffer.from([0x50, 0x4b, 0x05, 0x06]);
                                  ^
TypeError: this is not a typed array.
  at Function.from (na  at Object.<anonymous> (node_modules/gulp-zip/node_modules/yazl/index.js:111:35)
```
I forked gulp-zip and hardcoded yazl to use version 2.4.3 till this is fixed. Hopefully will be fixed soon.

**Comment by deepakpadukone20** [comment]
for node node < v4  
function bufferFrom(content) {
  try {
    return Buffer.from(content);
  } catch(e) {
    if (Object.prototype.toString.call(content) !== '[object String]') {
      throw new TypeError("separator must be a string");
    }
    return new Buffer(content);
  }
}

**Comment by deepakpadukone20** [comment]
for node < v4 we need to have something like below instead of directly using **Buffer.from**
```
function bufferFrom(content) {
  try {
    return Buffer.from(content);
  } catch(e) {
    if (Object.prototype.toString.call(content) !== '[object String]') {
      throw new TypeError("separator must be a string");
    }
    return new Buffer(content);
  }
}

```

**Comment by chetankh23** [comment]
When can we expect the fix for this to be released ?

**Comment by thejoshwolfe** [comment]
I've just gotten travis set up to test yazl against old versions of node. I should be able to fix this tonight.

**Comment by thejoshwolfe** [comment]
yazl version 2.5.1 is now published. This should resolve all the compatibility issues.

Thank you all for your patience!
