### ISSUE TITLE
[Question] .xapk support for zipping/unzipping?

### ISSUE THREAD

**Issue by Morsmalleo** [thejoshwolfe/yazl#73]
G'day guys, I came across your repository and it seems great, exactly what I'm looking for, just have a quick question, I want to know if this supports unzipping for `.xapk` files? hope I'm not wasting time by asking 🙂

**Comment by thejoshwolfe** [comment]
Hi @Morsmalleo sorry for the delayed response.

I'm not familiar with `.xapk` files. yazl creates zip files, so if that's good enough to create `.xapk` files, then I hope it works! If you can link me to the file format/specification for `.xapk` I can check if there are any special restrictions that may be incompatible with yazl. So far, my searching has suggested that they're regular zip files, just like `.apk`, however I vaguely recall that `.apk` files are prefixed with 3 bytes that aren't part of the zip file format?

I don't have any `.xapk` (or `.apk`) files to examine, and I don't have any way to verify if an `.xapk` file created by yazl were acceptable, so I think the most direct answer to your question is "no, yazl does not support `.xapk`", but that doesn't mean it won't work! Might be worth a try?

Let me know if you find a specification document.
