### ISSUE TITLE
[Idea]: allow setting the compression level

### ISSUE THREAD

**Issue by matteosacchetto** [thejoshwolfe/yazl#84]
I was investigating the code of this library, and I've seen that it takes advantage of `node:zlib`'s `deflateRaw` class/functions.

Given that `zlib`'s compression methods typically accept a parameter which is the compression level (between 1 and 9, defaults to 6), I was wondering if it could be interesting/worth exposing that parameter. It would allow a user of the library, to tune the compression level based on time/disk space.

To implement it, I think we could do one of the following:
- `entry.compress`: instead of restricting it to be a `boolean`, we could allow it to be a `boolean | number`, where if it is a `false` or `0`, no compression, if it is `true`, default compression level, otherwise the level is set based on `entry.compress`
- `entry.level`: have an additional parameter which specifies the level

I do not know how many users could be interested in this kind of feature, so I am leaving it here just as an idea, hoping to get some feedback from library users

**Comment by thejoshwolfe** [comment]
great idea! easy to support.

**Comment by thejoshwolfe** [comment]
published in version 3.2.0

**Comment by matteosacchetto** [comment]
Great to hear that!
I was checking the PR and I have a quick question
https://github.com/thejoshwolfe/yazl/blob/dc85d0b2cabb9f8f7c0f4888775eef340717c5e1/index.js#L97-L99
In the `addBuffer` method (the lines highlighted above), I see that the level is set to `1`. Shouldn't it be `entry.compressionLevel`? Or is there a reason for the fixed value?

Thank you in advance!

**Comment by thejoshwolfe** [comment]
Good catch! that's a typo. oops. I even have a test that makes sure the compression level is passed to zlib, but i only tested it for `addFile()` :facepalm: 

fix published in 3.2.1.
